openapi: 3.0.1
info:
  title: Services.AutoTrading Account Values Clients API
  description: 'The AutoTrading service group provides endpoints for interacting with Saxo Bank''s SaxoSelect offering.Through these interfaces a client application can get Saxo Select trade leaders, portfolios and investments. Portfolio investments can be created and modifed.<div class=well style=''border: 1px solid rgb(204, 82, 0); border-image: none; background-color: rgb(255, 209, 179);padding:1px;''><strong> Note:</strong> </br>This service is subject to special licensing agreements and not generally available to all OpenAPI applications.</div>'
  version: 2.4.138+710c760591
  x-framework-version: 38.0.2+439c5b0ec3
  x-machine: SIMOAWEB11-DK2
servers:
- url: https://gateway.saxobank.com/sim/openapi
tags:
- name: Clients
  description: "End points serving client related resources\n            The set of clients is restricted by the supplied query parameters as well as whether or not the identity \n            represented by the authorization token has access to the client."
paths:
  /port/v1/clients:
    get:
      tags:
      - Clients
      summary: Get details about clients under a particular owner
      description: This endpoint will return information for all clients under the specified owner as well as the owner itself.
      operationId: ClientsV1GetClients
      parameters:
      - name: $inlinecount
        in: query
        description: Specifies that the response to the request should include a count of the number of entries in the collection
        schema:
          enum:
          - AllPages
          - None
          type: string
          x-enum-descriptions:
            None: The result will not contain an inline count
            AllPages: The result will contain a total count of items in the queried collection
        example: AllPages
      - name: $skip
        in: query
        description: The number of entries to skip from the beginning of the collection
        schema:
          minimum: 0
          type: integer
          format: int32
        example: 1
      - name: $top
        in: query
        description: The number of entries to return from the beginning of the collection
        schema:
          minimum: 0
          type: integer
          format: int32
          default: 1000
        example: 1
      - name: OwnerKey
        in: query
        description: 'Unique key identifying the owner. This is the clientKey of the client under which the list of clients belongs. Default: Logged-in user''s client.'
        schema:
          title: 'Unique key identifying the owner. This is the clientKey of the client under which the list of clients belongs. Default: Logged-in user''s client.'
          minLength: 1
          type: string
          x-type-name: ClientKey
        example: 493b43a5-fe85-4d1f-9071-dd4a9d4e42a4
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponseListResult'
              example:
                __next: /openapi/port/....../?$top=1&$skip=1
                Data:
                - AllowedTradingSessions: Regular
                  ClientId: '654321'
                  ClientKey: V-B8jOk9SM8QdqN1u2Bjtw==
                  CurrencyDecimals: 0
                  DefaultAccountId: 192134INET
                  DefaultAccountKey: uke8gbCUrk6l7TnS5fnIdQ==
                  DefaultCurrency: EUR
                  ForceOpenDefaultValue: false
                  IsMarginTradingAllowed: false
                  IsVariationMarginEligible: false
                  LegalAssetTypes:
                  - Stock
                  - FxSpot
                  - CfdOnStock
                  - Bond
                  - ContractFutures
                  LegalAssetTypesAreIndicative: false
                  MarginCalculationMethod: Default
                  Name: Mr. Anthony Test
                  PositionNettingMethod: FIFO
                  PositionNettingMode: EndOfDay
                  PositionNettingProfile: FifoEndOfDay
                  ReduceExposureOnly: false
                  SupportsAccountValueProtectionLimit: false
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - InvalidClientId
                    - OwnerKeyMissing
                    - RequestContainsOwnerKeyAndEntityRelations
                    type: string
                    example: None
                    x-enum-descriptions:
                      InvalidClientId: Indicates that the requested client id was invalid.
                      OwnerKeyMissing: No valid input owner key specified.
                      RequestContainsOwnerKeyAndEntityRelations: Request can not contain both OwnerKey and EntityRelations.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Read
        community: Read
    patch:
      tags:
      - Clients
      summary: Enables IB to switch position netting mode(or netting profile) and change AccountValueProtectionLimit
      description: Enables IB to switch  position netting mode(or netting profile) and change account value protection limit on behalf of its clients.
      operationId: ClientsV1UpdateClientSettingsForPartner
      parameters:
      - name: ClientKey
        in: query
        description: clientKey of the client that to switch.
        required: true
        schema:
          minLength: 1
          type: string
          x-type-name: ClientKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientUpdateRequest'
            example:
              AccountValueProtectionLimit: 10
              ForceOpenDefaultValue: false
              NewPositionNettingMode: Intraday
              NewPositionNettingProfile: FifoEndOfDay
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - ClientPositionNettingModeSwitchNotAllowed
                    - ClientPositionNettingModeSwitchNotAllowedByConfiguration
                    - InvalidInput
                    type: string
                    example: None
                    x-enum-descriptions:
                      InvalidInput: An error was encountered when processing given input parameters.
                      ClientPositionNettingModeSwitchNotAllowed: All orders related to positions must be removed before real-time netting can be enabled.
                      ClientPositionNettingModeSwitchNotAllowedByConfiguration: The partner configuration does not allow changing the Netting Mode. No changes have been made.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Write
  /port/v1/clients/{ClientKey}:
    get:
      tags:
      - Clients
      summary: Get client details
      description: Get details about a client
      operationId: GET_ClientsV1GetClient
      parameters:
      - name: ClientKey
        in: path
        description: Unique key identifying the Client.
        required: true
        schema:
          minLength: 1
          type: string
          x-type-name: ClientKey
        example: 5DG7K1P5cqYBZ77tl7Af4w==
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
              example:
                AllowedTradingSessions: Regular
                ClientId: '654321'
                ClientKey: V-B8jOk9SM8QdqN1u2Bjtw==
                CurrencyDecimals: 0
                DefaultAccountId: 192134INET
                DefaultAccountKey: uke8gbCUrk6l7TnS5fnIdQ==
                DefaultCurrency: EUR
                ForceOpenDefaultValue: false
                IsMarginTradingAllowed: false
                IsVariationMarginEligible: false
                LegalAssetTypes:
                - Stock
                - FxSpot
                - CfdOnStock
                - Bond
                - ContractFutures
                LegalAssetTypesAreIndicative: false
                MarginCalculationMethod: Default
                Name: Mr. Anthony Test
                PositionNettingMethod: FIFO
                PositionNettingMode: EndOfDay
                PositionNettingProfile: FifoEndOfDay
                ReduceExposureOnly: false
                SupportsAccountValueProtectionLimit: false
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - InvalidClientId
                    type: string
                    example: None
                    x-enum-descriptions:
                      InvalidClientId: Indicates that the requested client id was invalid.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Read
        community: Read
  /port/v1/clients/me:
    get:
      tags:
      - Clients
      summary: Get logged in client details
      description: Get details about logged-in user's client
      operationId: ClientsV1GetClient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientResponse'
              example:
                AllowedTradingSessions: Regular
                ClientId: '654321'
                ClientKey: V-B8jOk9SM8QdqN1u2Bjtw==
                CurrencyDecimals: 0
                DefaultAccountId: 192134INET
                DefaultAccountKey: uke8gbCUrk6l7TnS5fnIdQ==
                DefaultCurrency: EUR
                ForceOpenDefaultValue: false
                IsMarginTradingAllowed: false
                IsVariationMarginEligible: false
                LegalAssetTypes:
                - Stock
                - FxSpot
                - CfdOnStock
                - Bond
                - ContractFutures
                LegalAssetTypesAreIndicative: false
                MarginCalculationMethod: Default
                Name: Mr. Anthony Test
                PositionNettingMethod: FIFO
                PositionNettingMode: EndOfDay
                PositionNettingProfile: FifoEndOfDay
                ReduceExposureOnly: false
                SupportsAccountValueProtectionLimit: false
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Read
        community: Read
    patch:
      tags:
      - Clients
      summary: Enables user to switch position netting mode or netting profile
      description: Enables user of the client to switch position netting mode or netting profile of its own.
      operationId: ClientsV1UpdateClientSettings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientUpdateRequest'
            example:
              AccountValueProtectionLimit: 10
              ForceOpenDefaultValue: false
              NewPositionNettingMode: Intraday
              NewPositionNettingProfile: FifoEndOfDay
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - ClientPositionNettingModeSwitchNotAllowed
                    - ClientPositionNettingModeSwitchNotAllowedByConfiguration
                    - InvalidInput
                    type: string
                    example: None
                    x-enum-descriptions:
                      InvalidInput: An error was encountered when processing given input parameters.
                      ClientPositionNettingModeSwitchNotAllowed: All orders related to positions must be removed before real-time netting can be enabled.
                      ClientPositionNettingModeSwitchNotAllowedByConfiguration: The partner configuration does not allow changing the Netting Mode. No changes have been made.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Write
components:
  schemas:
    ClientPositionNettingMode:
      title: Client's  position netting mode
      enum:
      - EndOfDay
      - Intraday
      type: string
      example: EndOfDay
      x-enum-descriptions:
        EndOfDay: Default EndOfDay netting mode.
        Intraday: Intraday netting mode.
    ClientUpdateRequest:
      title: A parameter wrapper for updating client values.
      type: object
      properties:
        AccountValueProtectionLimit:
          title: "If set, this value shields the total client value from going below the given limit by automatically triggering closing of positions should the limit be exceeded.\n            A limit of zero means there is no limit."
          type: number
          example: 10
        ForceOpenDefaultValue:
          title: If True, the order(s) placed by default will be set to force open , therfore resulting positions will not automatically be netted with positions in the opposite direction
          type: boolean
          example: true
        NewPositionNettingMode:
          title: The position netting mode, client would like to switch to.
          allOf:
          - $ref: '#/components/schemas/ClientPositionNettingMode'
        NewPositionNettingProfile:
          title: The position netting profile, client would like to switch to.
          allOf:
          - $ref: '#/components/schemas/ClientPositionNettingProfile'
      additionalProperties: false
      example:
        AccountValueProtectionLimit: 10
        ForceOpenDefaultValue: false
        NewPositionNettingMode: Intraday
        NewPositionNettingProfile: FifoEndOfDay
    ClientContractType:
      title: Clients Contract Types
      enum:
      - JointAccount
      type: string
      example: JointAccount
      x-enum-descriptions:
        JointAccount: Joint account
    MarginMonitoringMode:
      title: Margin Monitoring Mode.
      enum:
      - Equity
      - Lines
      - Margin
      type: string
      example: Lines
      x-enum-descriptions:
        Margin: Monitoring (stop-out's) are based on standard margin utilization, pre-check's are done against standard margin utilization.
        Lines: Monitoring (stop-out's) are based on credit line utilization, pre-check's are done against trading and credit line utilization.
        Equity: Monitoring is based on standard equity utilization, pre-check's are done against standard equity utilization.
    AllowedTradingSessions:
      title: Allowed trading sessions. Default value "Regular".
      enum:
      - All
      - Regular
      type: string
      example: Regular
      x-enum-descriptions:
        Regular: Default value. Regular trading hours session.
        All: Extended trading hours session.
    AssetType:
      title: The possible AssetTypes for which you can get a quote or place an order or a trade.
      enum:
      - Bond
      - Cash
      - CertificateBonus
      - CertificateCappedBonus
      - CertificateCappedCapitalProtected
      - CertificateCappedOutperformance
      - CertificateConstantLeverage
      - CertificateDiscount
      - CertificateExpress
      - CertificateTracker
      - CertificateUncappedCapitalProtection
      - CertificateUncappedOutperformance
      - CfdIndexOption
      - CfdOnCompanyWarrant
      - CfdOnEtc
      - CfdOnEtf
      - CfdOnEtn
      - CfdOnFund
      - CfdOnFutures
      - CfdOnIndex
      - CfdOnRights
      - CfdOnStock
      - CompanyWarrant
      - ContractFutures
      - Etc
      - Etf
      - Etn
      - Fund
      - FuturesOption
      - FuturesStrategy
      - FxBinaryOption
      - FxForwards
      - FxKnockInOption
      - FxKnockOutOption
      - FxNoTouchOption
      - FxOneTouchOption
      - FxSpot
      - FxVanillaOption
      - GuaranteeNote
      - IpoOnStock
      - ManagedFund
      - MiniFuture
      - MutualFund
      - PortfolioNote
      - Rights
      - SrdOnEtf
      - SrdOnStock
      - Stock
      - StockIndex
      - StockIndexOption
      - StockOption
      - Warrant
      - WarrantDoubleKnockOut
      - WarrantKnockOut
      - WarrantOpenEndKnockOut
      - WarrantSpread
      type: string
      example: FxForwards
      x-enum-descriptions:
        FxSpot: Forex Spot.
        FxForwards: Forex Forward.
        FxVanillaOption: Forex Vanilla Option.
        FxKnockInOption: Forex Knock In Option.
        FxKnockOutOption: Forex Knock Out Option.
        FxBinaryOption: Forex Binary Option.
        FxOneTouchOption: Forex One Touch Option.
        FxNoTouchOption: Forex No Touch Option.
        ContractFutures: Contract Futures.
        FuturesStrategy: Futures Strategy.
        Stock: Stock.
        StockOption: Stock Option.
        Bond: Bond.
        FuturesOption: Futures Option.
        StockIndexOption: Stock Index Option.
        ManagedFund: 'Obsolete: Managed Fund.'
        Cash: Cash. Not tradeable!
        CfdOnStock: Cfd on Stock.
        CfdOnIndex: Cfd on Stock Index.
        CfdOnFutures: Cfd on Futures.
        StockIndex: Stock Index.
        MutualFund: Mutual Fund.
        CfdIndexOption: Cfd Index Option.
        CfdOnEtf: Cfd on Etf
        CfdOnEtc: Cfd on Etc
        CfdOnEtn: Cfd on Etn
        CfdOnFund: Cfd on Fund
        CfdOnRights: Cfd on Rights
        CfdOnCompanyWarrant: Cfd on unlisted warrant issued by a corporation.
        Etf: Exchange traded fund.
        Etc: Etc
        Etn: Etn
        Fund: Fund
        Rights: Rights
        Warrant: Warrant
        MiniFuture: MiniFuture.
        WarrantSpread: Warrant with built-in spread.
        WarrantKnockOut: Warrant with a knock-out barrier.
        WarrantOpenEndKnockOut: Knock-out Warrant with no expiry.
        WarrantDoubleKnockOut: Warrant with two knock-out barriers.
        CertificateUncappedCapitalProtection: Guarantees a percentage increase of the underlying asset's value above the issue price at expiry/maturity. Max loss is the amount invested multiplied by the CapitalProtection percentage.
        CertificateCappedCapitalProtected: Guarantees a capped percentage increase of the underlying asset's value above the issue price at expiry/maturity. Max loss is the amount invested multiplied by the CapitalProtection percentage.
        CertificateDiscount: Yields a capped return if the underlying asset's value is above the specified cap level at expiry. If the underlying's value is below the strike at expiry, the investor received the underlying or equivalent value. Offers direct exposure in underlying at a lower price (discount) with a capped potential profit and limited loss.
        CertificateCappedOutperformance: Capped Outperformance Certificate.
        CertificateCappedBonus: Certificate Capped Bonus.
        CertificateExpress: Certificate Express kick out.
        CertificateTracker: A certificate that mirrors the price movement of the underlying instrument. Often used to trade movements in indicies. Movements can be a fixed ratio of the underlying and can be inverted for bearish/short speculation. Risk is equivalent to owning the underlying.
        CertificateUncappedOutperformance: Provides leveraged returns when the underlying price exceeds the threshold strike price. The amount leverage is defined by the Participation %. When the underlying is below the strike price, the certificate mirrors the underlying price 1:1.
        CertificateBonus: Mirrors the price movement of the underlying only if and when the underlying price exceeds the defined barrier. If the certificate expires below the barrier, it offers partial protection/return of investment.
        CertificateConstantLeverage: Certificate Constant Leverage.
        SrdOnStock: SRD. (Service de Règlement Différé) on Stock.
        SrdOnEtf: SRD. (Service de Règlement Différé) on Etf.
        IpoOnStock: IPO on Stock
        CompanyWarrant: Unlisted warrant issued by a corporation, often physically settled.
        PortfolioNote: Danish pooled investment scheme (“Pulje”). Not online tradeable.
        GuaranteeNote: Danish investment scheme (“Grantbevis”). Not online tradeable.
    PortfolioMarginMethod:
      title: Specifies the margin calculaion method for the given entity.
      enum:
      - Default
      - JanusMarginReplication
      - SpanForFutures
      - SpanForFuturesAndOptions
      type: string
      example: SpanForFutures
      x-enum-descriptions:
        Default: Uses Saxo exposure based margin.
        SpanForFutures: Uses rules-based SPAN methods to calculate margin on futures alone.
        SpanForFuturesAndOptions: Uses rules-based SPAN methods to calculate margin on futures and options.
        JanusMarginReplication: Uses rules-based the Janus methodology to calculate margin.
    SecurityLendingEnabled:
      title: Security Lending Enabled.
      enum:
      - false
      - true
      type: string
      example: true
      x-enum-descriptions:
        true: Security Lending is enabled.
        false: Security Lending is disabled.
    ClientResponse:
      title: Public data contract representing a client.
      type: object
      properties:
        AccountValueProtectionLimit:
          title: "If set, this value shields the total client value from going below the given limit by automatically triggering closing of positions should the limit be exceeded.\n            A limit of zero means there is no limit."
          type: number
          example: 10
        AllowedNettingProfiles:
          title: Allowed Netting Profiles for Client.
          type: array
          items:
            $ref: '#/components/schemas/ClientPositionNettingProfile'
          example:
          - FifoRealTime
        AllowedTradingSessions:
          title: Indicates if the client is allowed for extended trading hours.
          allOf:
          - $ref: '#/components/schemas/AllowedTradingSessions'
        ClientId:
          title: Unique ID of the client - for display to the user.
          type: string
          example: stringValue
        ClientKey:
          title: The unique key for the client.
          minLength: 1
          type: string
          x-type-name: ClientKey
        CollateralMonitoringMode:
          title: "Collateral Monitoring Mode.\n            Null when entity is not monitored on collateral."
          allOf:
          - $ref: '#/components/schemas/CollateralMonitoringMode'
        ContractType:
          title: "Client Contract Type.\n            Null if Client contract doesn’t belong to joint account."
          allOf:
          - $ref: '#/components/schemas/ClientContractType'
        CurrencyDecimals:
          title: Number of decimals used in currency.
          type: integer
          format: int32
          example: 99
        DefaultAccountId:
          title: The default account for this client.
          type: string
          example: stringValue
        DefaultAccountKey:
          title: The unique key for the client's default account.
          minLength: 1
          type: string
          x-type-name: AccountKey
        DefaultCurrency:
          title: 'The default currency for this client. Used for example for aggregation: if the client has accounts in multiple currencies, show the aggregated P/L in the this currency.'
          type: string
          example: stringValue
        ForceOpenDefaultValue:
          title: If True, the order(s) placed by default will be set to force open , therfore resulting positions will not automatically be netted with positions in the opposite direction.
          type: boolean
          example: true
        IsMarginTradingAllowed:
          title: Indicates whether trading on margin is allowed for the account.
          type: boolean
          example: true
        IsVariationMarginEligible:
          title: Indicates if the client is enabled for withdrawal of unrealized profit/loss of derivatives positions.
          type: boolean
          example: true
        LegalAssetTypes:
          title: The combined list of asset types, which can be traded on at least one of the accounts owned by this client.
          type: array
          items:
            $ref: '#/components/schemas/AssetType'
          example:
          - FxVanillaOption
        LegalAssetTypesAreIndicative:
          title: Certain clients have LegalAssetTypes on the account level and there may be instrument specific exceptions, so the client application must look up the individual instruments in Ref/InstrumentDetails to determine trade and prices permissions.
          type: boolean
          example: true
        MarginCalculationMethod:
          title: Calculation method for assessing margin utilization.
          allOf:
          - $ref: '#/components/schemas/PortfolioMarginMethod'
        MarginMonitoringMode:
          title: "Margin Monitoring Mode.\n            Null when entity is not monitored on margin."
          allOf:
          - $ref: '#/components/schemas/MarginMonitoringMode'
        MutualFundsCashAmountOrderCurrency:
          title: Indicates the currency used when placing MutualFunds orders with OrderAmountType.CashAmount.
          allOf:
          - $ref: '#/components/schemas/MutualFundsCashAmountOrderCurrency'
        Name:
          title: The name of the client.
          type: string
          example: stringValue
        PositionNettingMethod:
          title: The position netting method for this client.
          allOf:
          - $ref: '#/components/schemas/ClientPositionNettingMethod'
        PositionNettingMode:
          title: The position netting mode for this client.
          allOf:
          - $ref: '#/components/schemas/ClientPositionNettingMode'
        PositionNettingProfile:
          title: The position netting profile for this client.
          allOf:
          - $ref: '#/components/schemas/ClientPositionNettingProfile'
        ReduceExposureOnly:
          title: If True, Client has been marked to reduce exposure.
          type: boolean
          example: true
        SecurityLendingEnabled:
          title: Indicates if the client is enabled for security lending.
          allOf:
          - $ref: '#/components/schemas/SecurityLendingEnabled'
        SupportsAccountValueProtectionLimit:
          title: If true, an AccountValueProtectionLimit may be set on the client level. If it is false, the AccountValueProtectionLimit must be set on individual accounts or on account group level.
          type: boolean
          example: true
      additionalProperties: false
      example:
        AllowedTradingSessions: Regular
        ClientId: '654321'
        ClientKey: V-B8jOk9SM8QdqN1u2Bjtw==
        CurrencyDecimals: 0
        DefaultAccountId: 192134INET
        DefaultAccountKey: uke8gbCUrk6l7TnS5fnIdQ==
        DefaultCurrency: EUR
        ForceOpenDefaultValue: false
        IsMarginTradingAllowed: false
        IsVariationMarginEligible: false
        LegalAssetTypes:
        - Stock
        - FxSpot
        - CfdOnStock
        - Bond
        - ContractFutures
        LegalAssetTypesAreIndicative: false
        MarginCalculationMethod: Default
        Name: Mr. Anthony Test
        PositionNettingMethod: FIFO
        PositionNettingMode: EndOfDay
        PositionNettingProfile: FifoEndOfDay
        ReduceExposureOnly: false
        SupportsAccountValueProtectionLimit: false
    ModelStateDictionary:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    MutualFundsCashAmountOrderCurrency:
      title: Indicates the currency used when placing orders with OrderAmountType.CashAmount.
      enum:
      - Account
      - Instrument
      type: string
      example: Account
      x-enum-descriptions:
        Account: Use the specified account currency.
        Instrument: Use the currency of the specified instrument.
    ClientPositionNettingProfile:
      title: Client's position netting profile
      enum:
      - AverageRealTime
      - FifoEndOfDay
      - FifoRealTime
      type: string
      example: AverageRealTime
      x-enum-descriptions:
        AverageRealTime: AverageRealTime netting profile
        FifoRealTime: FifoRealTime netting profile
        FifoEndOfDay: FifoEndOfDay netting profile
    ClientPositionNettingMethod:
      title: Client's  position netting method
      enum:
      - Average
      - FIFO
      type: string
      example: FIFO
      x-enum-descriptions:
        FIFO: FIFO Netting Method
        Average: Average Netting Method
    CollateralMonitoringMode:
      title: Collateral Monitoring Mode. Different monitoring modes will change the behavior of stop outs, pre-checks etc (For Collateral based entities).
      enum:
      - CollateralCreditValue
      - MaxOfCollateralCreditValueAndCollateralCreditLine
      type: string
      example: CollateralCreditValue
      x-enum-descriptions:
        MaxOfCollateralCreditValueAndCollateralCreditLine: Monitoring (stop-out's) are based on collateral credit value and collateral credit line.
        CollateralCreditValue: Monitoring (stop-out's) are based on collateral credit value
    ClientResponseListResult:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/ClientResponse'
          description: The collection of entities for this feed.
        MaxRows:
          type: number
          description: The maximum number of rows that can be returned (if applicable).
        __count:
          type: number
          description: The total count of items in the feed.
        __next:
          type: string
          description: The link for the next page of items in the feed.
      additionalProperties: false
      example:
        __next: /openapi/port/....../?$top=1&$skip=1
        Data:
        - AllowedTradingSessions: Regular
          ClientId: '654321'
          ClientKey: V-B8jOk9SM8QdqN1u2Bjtw==
          CurrencyDecimals: 0
          DefaultAccountId: 192134INET
          DefaultAccountKey: uke8gbCUrk6l7TnS5fnIdQ==
          DefaultCurrency: EUR
          ForceOpenDefaultValue: false
          IsMarginTradingAllowed: false
          IsVariationMarginEligible: false
          LegalAssetTypes:
          - Stock
          - FxSpot
          - CfdOnStock
          - Bond
          - ContractFutures
          LegalAssetTypesAreIndicative: false
          MarginCalculationMethod: Default
          Name: Mr. Anthony Test
          PositionNettingMethod: FIFO
          PositionNettingMode: EndOfDay
          PositionNettingProfile: FifoEndOfDay
          ReduceExposureOnly: false
          SupportsAccountValueProtectionLimit: false
  responses:
    ServiceUnavailable:
      description: Service Unavailable.
    Unauthorized:
      description: Indicates that the request was rejected because the 'Authorization' header was missing in the request or contained an invalid security token.
    TooManyRequests:
      description: The request was rejected due to rate limit being exceeded.
    BadRequest:
      description: One or more of the provided parameters are invalid.
      content:
        application/json:
          schema:
            required:
            - ErrorCode
            - Message
            type: object
            properties:
              ErrorCode:
                enum:
                - InvalidRequest
                type: string
                example: None
                x-enum-descriptions:
                  InvalidRequest: Default error code returned when it cannot be determined which part of the request is malformed.
              Message:
                type: string
              ModelState:
                $ref: '#/components/schemas/ModelStateDictionary'
  securitySchemes:
    OpenApiJWTSecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenApiOAuthSecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sim.logonvalidation.net/authorize
          tokenUrl: https://sim.logonvalidation.net/token
          scopes: {}
