openapi: 3.2.0
info:
  title: Services.PartnerIntegration Update pricing API
  description: PartnerIntegration provide end points for partner integration with saxo.
  version: 2.0.24+857498a42e
  x-framework-version: 43.0.5+65c0bdc8ab
  x-machine: SIMOAWEB10-DK1
servers:
- url: https://gateway.saxobank.com/sim/openapi
tags:
- name: Update pricing
  description: Provides non stream price update endpoint
paths:
  /partnerintegration/v1/instrumentprices:
    get:
      tags:
      - Update pricing
      description: 'Get the prices for unlisted instruments


        This endpoint supports OData query operators: $top and $skip.

        Default value of query operator $top is 1000 records and maximum value is 1000 records.'
      operationId: UpdatePricingGetPrices
      parameters:
      - name: $skip
        in: query
        description: The number of entries to skip from the beginning of the collection
        style: form
        explode: false
        schema:
          minimum: 0
          type: integer
          format: int32
        example: 1
      - name: $top
        in: query
        description: The number of entries to return from the beginning of the collection
        style: form
        explode: false
        schema:
          maximum: 1000
          minimum: 0
          type: integer
          format: int32
          default: 1000
        example: 1
      responses:
        '200':
          description: Indicates that the request is processed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceDetailListResult'
              example:
                __next: /openapi/....../?$top=1&$skip=1
                Data:
                - AssetType: Stock
                  Currency: USD
                  Description: Apple Inc.
                  LastUpdated: '2022-10-31T03:45:12.167463Z'
                  Price: 10
                  Uic: 122
        '404':
          description: Indicates that the request is not authorize to perform operation Or given client has not been configured for any feedbproviderid.
        '500':
          description: Indicates that the internal error occurred due to unhandled exception while processing request.
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Read
      summary: Update pricing get prices
      x-summary-source: derived
    post:
      tags:
      - Update pricing
      description: 'Update pricing


        Endpoint update the prices for unlisted uics.'
      operationId: UpdatePricingUpdatePrices
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PriceUpdateRequest'
            example:
              PriceUpdates:
              - AssetType: Bond
                LastUpdated: '2022-10-31T03:45:12.156462Z'
                Price: 100
                Uic: 211
      responses:
        '201':
          description: Created
        '404':
          description: Indicates that the request is not authorize to perform operation.
        '200':
          description: Indicates that the request is processed successfully.
        '400':
          description: Indicates that the request is invalid data content
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - InvalidRequest
                    type: string
                    example: None
                    x-enum-descriptions:
                      InvalidRequest: Default error code returned when it cannot be determined which part of the request is malformed.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '500':
          description: Indicates that the internal error occurred due to unhandled exception while processing request.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        personal: Read
      summary: Update pricing update prices
      x-summary-source: derived
components:
  responses:
    Unauthorized:
      description: Indicates that the request was rejected because the 'Authorization' header was missing in the request or contained an invalid security token.
    TooManyRequests:
      description: The request was rejected due to rate limit being exceeded.
    BadRequest:
      description: One or more of the provided parameters are invalid.
      content:
        application/json:
          schema:
            required:
            - ErrorCode
            - Message
            type: object
            properties:
              ErrorCode:
                enum:
                - InvalidRequest
                type: string
                example: None
                x-enum-descriptions:
                  InvalidRequest: Default error code returned when it cannot be determined which part of the request is malformed.
              Message:
                type: string
              ModelState:
                $ref: '#/components/schemas/ModelStateDictionary'
    ServiceUnavailable:
      description: Service Unavailable.
  schemas:
    PriceDetail:
      title: Price detail info
      type: object
      properties:
        AssetType:
          title: Instrument's asset type
          allOf:
          - $ref: '#/components/schemas/AssetType'
        Currency:
          title: Instrument's currency
          type: string
          example: stringValue
        Description:
          title: Instrument's description
          type: string
          example: stringValue
        LastUpdated:
          title: Instrument's last price updated date
          type: string
          format: date-time
          x-type-name: UtcDateTime
        Price:
          title: Instrument's price
          type: number
          example: 10
        Uic:
          title: Instrument's uic
          type: integer
          format: int32
          example: 99
      additionalProperties: false
      example:
        AssetType: FxNoTouchOption
        Currency: stringValue
        Description: stringValue
        LastUpdated: '9999-12-31T23:59:59.9999990+00:00'
        Price: 10
        Uic: 99
    PriceUpdate:
      title: Price update
      required:
      - AssetType
      - LastUpdated
      - Price
      - Uic
      type: object
      properties:
        AssetType:
          title: Asset type for instrument
          allOf:
          - $ref: '#/components/schemas/AssetType'
        LastUpdated:
          title: Last updated date for instrument
          type: string
          format: date-time
          x-type-name: UtcDateTime
        Price:
          title: Instrument's price
          type: number
          example: 10
        Uic:
          title: Instrument's uic
          type: integer
          format: int32
          example: 99
      additionalProperties: false
      example:
        AssetType: FxBinaryOption
        LastUpdated: '9999-12-31T23:59:59.9999990+00:00'
        Price: 10
        Uic: 99
    ModelStateDictionary:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    PriceUpdateRequest:
      title: Class for price update request
      type: object
      properties:
        PriceUpdates:
          title: List of price update
          type: array
          items:
            $ref: '#/components/schemas/PriceUpdate'
          example:
          - AssetType: FxOneTouchOption
            LastUpdated: '9999-12-31T23:59:59.999999Z'
            Price: 10
            Uic: 99
      additionalProperties: false
      example:
        PriceUpdates:
        - AssetType: Bond
          LastUpdated: '2022-10-31T03:45:12.156462Z'
          Price: 100
          Uic: 211
    PriceDetailListResult:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/PriceDetail'
          description: The collection of entities for this feed.
        MaxRows:
          type: number
          description: The maximum number of rows that can be returned (if applicable).
        __count:
          type: number
          description: The total count of items in the feed.
        __next:
          type: string
          description: The link for the next page of items in the feed.
      additionalProperties: false
      example:
        __next: /openapi/....../?$top=1&$skip=1
        Data:
        - AssetType: Stock
          Currency: USD
          Description: Apple Inc.
          LastUpdated: '2022-10-31T03:45:12.167463Z'
          Price: 10
          Uic: 122
    AssetType:
      title: The possible AssetTypes for which you can get a quote or place an order or a trade.
      enum:
      - Bond
      - Cash
      - CertificateBonus
      - CertificateCappedBonus
      - CertificateCappedCapitalProtected
      - CertificateCappedOutperformance
      - CertificateConstantLeverage
      - CertificateDiscount
      - CertificateExpress
      - CertificateTracker
      - CertificateUncappedCapitalProtection
      - CertificateUncappedOutperformance
      - CfdIndexOption
      - CfdOnCompanyWarrant
      - CfdOnEtc
      - CfdOnEtf
      - CfdOnEtn
      - CfdOnFund
      - CfdOnFutures
      - CfdOnIndex
      - CfdOnRights
      - CfdOnStock
      - CompanyWarrant
      - ContractFutures
      - Etc
      - Etf
      - Etn
      - Fund
      - FuturesOption
      - FuturesStrategy
      - FxBinaryOption
      - FxForwards
      - FxKnockInOption
      - FxKnockOutOption
      - FxNoTouchOption
      - FxOneTouchOption
      - FxSpot
      - FxVanillaOption
      - GuaranteeNote
      - IpoOnStock
      - ManagedFund
      - MiniFuture
      - MutualFund
      - PortfolioNote
      - Rights
      - SrdOnEtf
      - SrdOnStock
      - Stock
      - StockIndex
      - StockIndexOption
      - StockOption
      - Warrant
      - WarrantDoubleKnockOut
      - WarrantKnockOut
      - WarrantOpenEndKnockOut
      - WarrantSpread
      type: string
      example: FxKnockOutOption
      x-enum-descriptions:
        FxSpot: Forex Spot.
        FxForwards: Forex Forward.
        FxVanillaOption: Forex Vanilla Option.
        FxKnockInOption: Forex Knock In Option.
        FxKnockOutOption: Forex Knock Out Option.
        FxBinaryOption: Forex Binary Option.
        FxOneTouchOption: Forex One Touch Option.
        FxNoTouchOption: Forex No Touch Option.
        ContractFutures: Contract Futures.
        FuturesStrategy: Futures Strategy.
        Stock: Stock.
        StockOption: Stock Option.
        Bond: Bond.
        FuturesOption: Futures Option.
        StockIndexOption: Stock Index Option.
        ManagedFund: 'Obsolete: Managed Fund.'
        Cash: Cash. Not tradeable!
        CfdOnStock: Cfd on Stock.
        CfdOnIndex: Cfd on Stock Index.
        CfdOnFutures: Cfd on Futures.
        StockIndex: Stock Index.
        MutualFund: Mutual Fund.
        CfdIndexOption: Cfd Index Option.
        CfdOnEtf: Cfd on Etf
        CfdOnEtc: Cfd on Etc
        CfdOnEtn: Cfd on Etn
        CfdOnFund: Cfd on Fund
        CfdOnRights: Cfd on Rights
        CfdOnCompanyWarrant: Cfd on unlisted warrant issued by a corporation.
        Etf: Exchange traded fund.
        Etc: Etc
        Etn: Etn
        Fund: Fund
        Rights: Rights
        Warrant: Warrant
        MiniFuture: MiniFuture.
        WarrantSpread: Warrant with built-in spread.
        WarrantKnockOut: Warrant with a knock-out barrier.
        WarrantOpenEndKnockOut: Knock-out Warrant with no expiry.
        WarrantDoubleKnockOut: Warrant with two knock-out barriers.
        CertificateUncappedCapitalProtection: Guarantees a percentage increase of the underlying asset's value above the issue price at expiry/maturity. Max loss is the amount invested multiplied by the CapitalProtection percentage.
        CertificateCappedCapitalProtected: Guarantees a capped percentage increase of the underlying asset's value above the issue price at expiry/maturity. Max loss is the amount invested multiplied by the CapitalProtection percentage.
        CertificateDiscount: Yields a capped return if the underlying asset's value is above the specified cap level at expiry. If the underlying's value is below the strike at expiry, the investor received the underlying or equivalent value. Offers direct exposure in underlying at a lower price (discount) with a capped potential profit and limited loss.
        CertificateCappedOutperformance: Capped Outperformance Certificate.
        CertificateCappedBonus: Certificate Capped Bonus.
        CertificateExpress: Certificate Express kick out.
        CertificateTracker: A certificate that mirrors the price movement of the underlying instrument. Often used to trade movements in indicies. Movements can be a fixed ratio of the underlying and can be inverted for bearish/short speculation. Risk is equivalent to owning the underlying.
        CertificateUncappedOutperformance: Provides leveraged returns when the underlying price exceeds the threshold strike price. The amount leverage is defined by the Participation %. When the underlying is below the strike price, the certificate mirrors the underlying price 1:1.
        CertificateBonus: Mirrors the price movement of the underlying only if and when the underlying price exceeds the defined barrier. If the certificate expires below the barrier, it offers partial protection/return of investment.
        CertificateConstantLeverage: Certificate Constant Leverage.
        SrdOnStock: SRD. (Service de Règlement Différé) on Stock.
        SrdOnEtf: SRD. (Service de Règlement Différé) on Etf.
        IpoOnStock: IPO on Stock
        CompanyWarrant: Unlisted warrant issued by a corporation, often physically settled.
        PortfolioNote: Danish pooled investment scheme (“Pulje”). Not online tradeable.
        GuaranteeNote: Danish investment scheme (“Grantbevis”). Not online tradeable.
  securitySchemes:
    OpenApiJWTSecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenApiOAuthSecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sim.logonvalidation.net/authorize
          tokenUrl: https://sim.logonvalidation.net/token
          scopes: {}
