openapi: 3.2.0
info:
  title: Services.ReferenceData Languages API
  description: The Reference Data service group provides reference data, such as instrument details, exchange info etc..
  version: 2.3.361+88ada090e4
  x-framework-version: 43.0.9+b005aba300
  x-machine: SIMOAWEB8-DK2
servers:
- url: https://gateway.saxobank.com/sim/openapi
tags:
- name: Languages
  description: End points serving ISO 639-1 language information
paths:
  /ref/v1/languages:
    get:
      tags:
      - Languages
      summary: Get all supported languages
      description: Returns a list containing all the languages supported by Saxo Bank.
      operationId: LanguagesGet
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LanguageDetailsListResult'
              example:
                __next: /openapi/....../?$top=1&$skip=1
                Data:
                - LanguageCode: en
                  LanguageName: English
                  NativeName: English
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        restricted: Read
components:
  responses:
    Unauthorized:
      description: Indicates that the request was rejected because the 'Authorization' header was missing in the request or contained an invalid security token.
    TooManyRequests:
      description: The request was rejected due to rate limit being exceeded.
    BadRequest:
      description: One or more of the provided parameters are invalid.
      content:
        application/json:
          schema:
            required:
            - ErrorCode
            - Message
            type: object
            properties:
              ErrorCode:
                enum:
                - InvalidRequest
                type: string
                example: None
                x-enum-descriptions:
                  InvalidRequest: Default error code returned when it cannot be determined which part of the request is malformed.
              Message:
                type: string
              ModelState:
                $ref: '#/components/schemas/ModelStateDictionary'
    ServiceUnavailable:
      description: Service Unavailable.
  schemas:
    LanguageDetails:
      title: Represents a language.
      type: object
      properties:
        LanguageCode:
          title: "The ISO 639-1 two-letter language code. (Except for zh-cn and zh-tw).\n            This list only includes languages for which Saxo has full or partial support for translation of texts."
          pattern: ^[a-zA-Z]{2}(-[A-Z]{2})?$
          type: string
          x-type-name: LanguageCode
        LanguageName:
          title: The name of the language (in English).
          type: string
          example: stringValue
        NativeName:
          title: The name of the language (in native language).
          type: string
          example: stringValue
      additionalProperties: false
      example:
        LanguageCode: en
        LanguageName: English
        NativeName: English
    LanguageDetailsListResult:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/LanguageDetails'
          description: The collection of entities for this feed.
        MaxRows:
          type: number
          description: The maximum number of rows that can be returned (if applicable).
        __count:
          type: number
          description: The total count of items in the feed.
        __next:
          type: string
          description: The link for the next page of items in the feed.
      additionalProperties: false
      example:
        __next: /openapi/....../?$top=1&$skip=1
        Data:
        - LanguageCode: en
          LanguageName: English
          NativeName: English
    ModelStateDictionary:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
  securitySchemes:
    OpenApiJWTSecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenApiOAuthSecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sim.logonvalidation.net/authorize
          tokenUrl: https://sim.logonvalidation.net/token
          scopes: {}
