openapi: 3.0.1
info:
  title: Services.AutoTrading Account Values Partner - Cash Transfer Limits API
  description: 'The AutoTrading service group provides endpoints for interacting with Saxo Bank''s SaxoSelect offering.Through these interfaces a client application can get Saxo Select trade leaders, portfolios and investments. Portfolio investments can be created and modifed.<div class=well style=''border: 1px solid rgb(204, 82, 0); border-image: none; background-color: rgb(255, 209, 179);padding:1px;''><strong> Note:</strong> </br>This service is subject to special licensing agreements and not generally available to all OpenAPI applications.</div>'
  version: 2.4.138+710c760591
  x-framework-version: 38.0.2+439c5b0ec3
  x-machine: SIMOAWEB11-DK2
servers:
- url: https://gateway.saxobank.com/sim/openapi
tags:
- name: Partner - Cash Transfer Limits
  description: Provides endpoints for cash available for transfer.
paths:
  /atr/v1/partner/cashtransferlimits/{AccountKey}:
    get:
      tags:
      - Partner - Cash Transfer Limits
      description: Get available amount for transfer.
      operationId: PartnerCashTransferLimitGetCashTransfersLimitsAsync
      parameters:
      - name: AccountKey
        in: path
        description: Account Key
        required: true
        schema:
          minLength: 1
          type: string
          x-type-name: AccountKey
        example: ellzACrscBL2WPH6H6xADg==
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerAccountCashTransferLimit'
              example:
                AccountKey: sUyiJbnf57ayjlcoNp1RkA==
                CashTransferLimit: 100
                Currency: USD
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - NotNormalAccount
                    type: string
                    example: None
                    x-enum-descriptions:
                      NotNormalAccount: Account should be normal trading account.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - CashTransferLimitsNotFound
                    - ClientIsSameAsCallingClient
                    - ClientNotSameAsAccount
                    type: string
                    example: None
                    x-enum-descriptions:
                      ClientNotSameAsAccount: ClientKey and AccountKey both should have same client.
                      ClientIsSameAsCallingClient: Client in the request should not be same as calling client.
                      CashTransferLimitsNotFound: Cash transfer limits not found.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '503':
          description: Service Unavailable
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-required-permissions:
        confidential: Read
  /atr/v1/partner/cashtransferlimits:
    get:
      tags:
      - Partner - Cash Transfer Limits
      description: Obsolete Get available amount for transfer.
      operationId: PartnerCashTransferLimitGetCashTransfersLimits
      parameters:
      - name: AccountKey
        in: query
        description: AccountKey
        required: true
        schema:
          minLength: 1
          type: string
          x-type-name: AccountKey
      - name: ClientKey
        in: query
        description: ClientKey
        required: true
        schema:
          minLength: 1
          type: string
          x-type-name: ClientKey
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PartnerCashTransferLimitListResult'
              example:
                Data:
                - AccountKey: sUyiJbnf57ayjlcoNp1RkA==
                  ClientKey: W-CgwnsUEpETkiR8MPJalA==
                  MaxAllowedWithdrawalAmount: 100
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - NotNormalAccount
                    type: string
                    example: None
                    x-enum-descriptions:
                      NotNormalAccount: Account should be normal trading account.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                required:
                - ErrorCode
                - Message
                type: object
                properties:
                  ErrorCode:
                    enum:
                    - CashTransferLimitsNotFound
                    - ClientIsSameAsCallingClient
                    - ClientNotSameAsAccount
                    type: string
                    example: None
                    x-enum-descriptions:
                      ClientNotSameAsAccount: ClientKey and AccountKey both should have same client.
                      ClientIsSameAsCallingClient: Client in the request should not be same as calling client.
                      CashTransferLimitsNotFound: Cash transfer limits not found.
                  Message:
                    type: string
                  ModelState:
                    $ref: '#/components/schemas/ModelStateDictionary'
        '503':
          description: Service Unavailable
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
      deprecated: true
      security:
      - OpenApiOAuthSecurityScheme: []
      - OpenApiJWTSecurityScheme: []
      x-deprecated-date: '2023-01-01'
      x-required-permissions:
        confidential: Read
components:
  schemas:
    ModelStateDictionary:
      type: object
      additionalProperties:
        type: array
        items:
          type: string
    PartnerCashTransferLimit:
      title: CashWithdrawalLimit
      type: object
      properties:
        AccountKey:
          title: AccountKey
          minLength: 1
          type: string
          x-type-name: AccountKey
        ClientKey:
          title: ClientKey
          minLength: 1
          type: string
          x-type-name: ClientKey
        MaxAllowedWithdrawalAmount:
          title: Max allowed withdrawal amount
          type: number
          example: 2.55
      additionalProperties: false
      example:
        AccountKey: dIm75edbgnW6aBK3CIc-sw==
        ClientKey: zpSlGZ4F0cPIx59wR3HP1g==
        MaxAllowedWithdrawalAmount: 2.55
    PartnerCashTransferLimitListResult:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/PartnerCashTransferLimit'
          description: The collection of entities for this feed.
        MaxRows:
          type: number
          description: The maximum number of rows that can be returned (if applicable).
        __count:
          type: number
          description: The total count of items in the feed.
        __next:
          type: string
          description: The link for the next page of items in the feed.
      additionalProperties: false
      example:
        Data:
        - AccountKey: sUyiJbnf57ayjlcoNp1RkA==
          ClientKey: W-CgwnsUEpETkiR8MPJalA==
          MaxAllowedWithdrawalAmount: 100
    PartnerAccountCashTransferLimit:
      title: Cash transfer limit
      type: object
      properties:
        AccountKey:
          title: AccountKey
          minLength: 1
          type: string
          x-type-name: AccountKey
        CashTransferLimit:
          title: Maximal amount which can be transferred out.
          type: number
          example: 10
        Currency:
          title: Currency
          pattern: ^[A-Z]{3}$
          type: string
          x-type-name: CurrencyCode
      additionalProperties: false
      example:
        AccountKey: sUyiJbnf57ayjlcoNp1RkA==
        CashTransferLimit: 100
        Currency: USD
  responses:
    Unauthorized:
      description: Indicates that the request was rejected because the 'Authorization' header was missing in the request or contained an invalid security token.
    TooManyRequests:
      description: The request was rejected due to rate limit being exceeded.
  securitySchemes:
    OpenApiJWTSecurityScheme:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OpenApiOAuthSecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sim.logonvalidation.net/authorize
          tokenUrl: https://sim.logonvalidation.net/token
          scopes: {}
